# Generated by Django 5.2.4 on 2025-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('precio_moneda', models.CharField(default='USD', max_length=10)),
                ('precio_valor', models.IntegerField()),
                ('url_publicacion', models.URLField(max_length=500, unique=True)),
                ('url_imagen', models.URLField(max_length=500)),
                ('portal', models.CharField(default='mercadolibre', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('fecha_scrapeo', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
