# Generated by Django 5.2.4 on 2025-08-27 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inmobiliaria',
                'verbose_name_plural': 'Inmobiliarias',
                'db_table': 'inmobiliaria',
            },
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=100, unique=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('sinonimos', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'verbose_name_plural': 'Palabras Clave',
                'db_table': 'palabra_clave',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'plataforma',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plataforma')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'propiedad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inmobiliaria')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_busqueda', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_original', models.TextField()),
                ('filtros', models.JSONField(default=dict)),
                ('guardado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'db_table': 'busqueda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaPalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.busqueda')),
                ('palabra_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.palabraclave')),
            ],
            options={
                'verbose_name': 'Búsqueda - Palabra Clave',
                'verbose_name_plural': 'Búsquedas - Palabras Clave',
                'db_table': 'busqueda_palabra_clave',
                'unique_together': {('busqueda', 'palabra_clave')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoBusqueda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coincide', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.busqueda')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Resultado de Búsqueda',
                'verbose_name_plural': 'Resultados de Búsqueda',
                'db_table': 'resultado_busqueda',
                'unique_together': {('busqueda', 'propiedad')},
            },
        ),
    ]
