# Generated by Django 5.2.4 on 2025-08-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ciudad_barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
