# Generated by Django 5.2.4 on 2025-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propiedad_descripcion_propiedad_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='ultima_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadobusqueda',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadobusqueda',
            name='seen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['usuario', 'created_at'], name='busqueda_usuario_a06811_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['guardado', 'created_at'], name='busqueda_guardad_431ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['usuario', 'guardado'], name='busqueda_usuario_1bb4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='palabraclave',
            index=models.Index(fields=['texto'], name='palabra_cla_texto_74b9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='palabraclave',
            index=models.Index(fields=['idioma'], name='palabra_cla_idioma_c4eeae_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['plataforma', 'created_at'], name='propiedad_platafo_437986_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['created_at'], name='propiedad_created_73694b_idx'),
        ),
    ]
