# Generated by Django 5.2.4 on 2025-08-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propiedad_banos_propiedad_ciudad_barrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='operacion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
