# Generated by Django 5.2.4 on 2025-08-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propiedad_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='antiguedad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cocheras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_cubierta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
