# Generated by Django 5.2.4 on 2025-09-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_busqueda_ultima_revision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraClavePropiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encontrada', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palabra_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.palabraclave')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Palabra Clave - Propiedad',
                'verbose_name_plural': 'Palabras Clave - Propiedades',
                'db_table': 'palabra_clave_propiedad',
                'indexes': [models.Index(fields=['palabra_clave', 'encontrada'], name='palabra_cla_palabra_2ec9d2_idx'), models.Index(fields=['propiedad', 'encontrada'], name='palabra_cla_propied_af909c_idx')],
                'unique_together': {('palabra_clave', 'propiedad')},
            },
        ),
    ]
