# Generated by Django 5.2.4 on 2025-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propiedad_antiguedad_propiedad_cocheras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='admite_mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='caracteristicas_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='condicion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='es_amoblado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_terraza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_tour_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_inmueble',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='antiguedad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cocheras',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='dormitorios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio_moneda',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio_valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='superficie_cubierta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='superficie_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='url_imagen',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
