# Generated by Django 5.2.4 on 2025-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_palabraclavepropiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='intervalo_actualizacion_horas',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='max_actualizaciones_por_dia',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='max_busquedas_nuevas_por_dia',
            field=models.IntegerField(default=5),
        ),
    ]
