# Generated by Django 5.2.4 on 2025-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_propiedad_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='banos',
            new_name='banos_max',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='cocheras',
            new_name='banos_min',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='dormitorios',
            new_name='cocheras_max',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='superficie_cubierta',
            new_name='cocheras_min',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='superficie_total',
            new_name='dormitorios_max',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tiene_jardin',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tiene_piscina',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tiene_terraza',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tiene_tour_virtual',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_cubierta_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_cubierta_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_total_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_total_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
