# Generated by Django 5.2.4 on 2025-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_banos_propiedad_banos_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tiene_jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_terraza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_tour_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
